### ISSUE TITLE
Package updates

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/scikit-hep#173]
I'd like to propose we remove uproot-methods, uproot3, and awkward0. I think they are deprecated and not really being actively maintained. They should be opt in, not automatically included in the metapackage at this point. CC @jpivarski 

Also, hepstats[^1] seems rather dead. CC @jonas-eschle, I think.

I also think we consider our newcomers. Uproot-browser, perhaps? I'm thinking it might be better not to add "applications", though, like uproot-browser, or major independent (user) packages, like cabinetry, pyhf, etc. We probably should look through our packages and see if there are any that should be added to the "core" set. Maybe we could add a "core" or "metapackage" marker on the webpage to show which ones are part of the metapacakge? 

[^1]: Maybe it was another package. I know I saw one that didn't support Python 3.10 and had ~3 open PRs from me, and broken CI.

**Comment by jpivarski** [comment]
I agree: we don't want newcomers to think they should use uproot-methods, uproot3, or awkward0. Where are you suggesting they should go? A new organization called "scikit-hep-deprecated"?

Or maybe they should just become archived repos? (That would make it difficult to insert an emergency bug-fix, which I'm still open to, if it were a big enough emergency.)

If you're talking about packages that get pulled in by scikit-hep as a PyPI/conda package, then definitely. There's no reason they should be promoted as active.

**Comment by henryiii** [comment]
This is for removing them from the metadata package. I'd probably go with archiving, that makes it clear what the status is, and you can always un-archive if needed (though I don't think people can open issues on an archived repo). No rush or worry about that at the moment, I just noticed them in the metadata repo list.

https://github.com/scikit-hep/scikit-hep/blob/master/requirements.txt & https://github.com/scikit-hep/scikit-hep/blob/master/requirements_current_release.txt

**Comment by eduardo-rodrigues** [comment]
> I'd like to propose we remove uproot-methods, uproot3, and awkward0. I think they are deprecated and not really being actively maintained. They should be opt in, not automatically included in the metapackage at this point. CC @jpivarski

Sure. I have kept them since a while because we know "inertia" is exactly that. At this point in time you're right that it seems very reasonable to remove them from the metapackage, which is there to ease having a set of core packages. I will proceed tomorrow and will ping you both.

> Also, hepstats seems rather dead. CC @jonas-eschle, I think.

That's not quite true and in fact there were some exchanges on the admins list back in Nov. for a take-over of maintenance. This being said, it is true that maintenance has not been up to the required level, so there is some improvement to be made ;-). I believe Hans had some thoughts as well, but has been over-busy. In short, let's not remove it from the metapackage.

On archiving: I would not be too aggressive with the archival of core packages such as uproot3. It was not that long ago that I came across somebody still using it rather than uproot4. I would add now deprecation warnings as we did a while back for root_numpy and others. In a few months you would then archive them for good. My 2 cents, thinking about the user (a deprecated tag vs archival does not put extra maintenance for us while being a big more flexible for users).

I will look at the rest of the ideas tomorrow.

**Comment by jpivarski** [comment]
In terms of new Uproot/Awkward adoption, this is where we are (in linear scale):

![image](https://user-images.githubusercontent.com/1852447/160717483-15c2c515-7fda-498e-bfe4-3e00f13ef5cd.png)

![image](https://user-images.githubusercontent.com/1852447/160717526-d80ad468-e9f2-400b-a88d-239c83e269f2.png)

The log-scale for Awkward isn't very interesting, but for Uproot, you can see that there are still 1.x users!

![image](https://user-images.githubusercontent.com/1852447/160717648-9b5f233d-8974-410e-923b-7bd073fb35be.png)

Anyway, the main point is that most users are on Uproot 4/Awkward 1. In terms of engagement, very few people are submitting bug reports or asking questions about the old versions, but the new ones are active. That's what would matter for archiving them. (People can pin to Uproot 1.x if they want, but I don't know what they would do if they encounter a bug.)

**Comment by eduardo-rodrigues** [comment]
Your call, Jim. I will anyway remove those very old packages from the metapackage, as that's very safe and sound.

**Comment by eduardo-rodrigues** [comment]
Done in PR https://github.com/scikit-hep/scikit-hep/pull/174.

I looked for packages that one might add:
- `pyhf` and `cabinetry`: agree that they are major independent user packages that aren't needed by default in the metapackage. That's why I never included them. OK @matthewfeickert ?
- `uproot-browser` is super light but more an application. I would in fact add it, but let me know @henryiii and @jpivarski what's your take.
- `pylhe` is very lightweight but also really scoped. I do not see a strong case to add it. CC @matthewfeickert in case there's an argument for inclusion.
- `fastjet` is scoped but many people do jets. I would be tempted to add it at this point. @jpivarski ?
- `resample`: seems also very scoped. No strong feelings. Do you feel we should add it to the metapackage, @HDembinski ?

**Comment by alexander-held** [comment]
The question of what to include comes down to who the target audience for this package is (apologies if that has been discussed previously elsewhere!). Are we aiming to provide
- a single package that provides an exhaustive set of tools covering many possible user needs,
- or a more focused set of core dependencies from which we expect that most users use the majority of them?

In addition, in which context do users install this? It could be a catch-all install in a new environment to quickly get set up, in which case I think it is helpful to include a wide set of packages. If users already have specific workflows in mind, the overhead of building a targeted environment with the exact requirements (skipping the meta-package) does not seem too large to me, and may be preferable for other reasons (e.g. minimizing potential for conflicts).

Many of the packages currently included fall into the "core" category in my opinion. There are some exceptions from an ATLAS perspective, `hepstats` and `decaylanguage` both to me seem like they would be used less than `pyhf` and `pylhe`.

**Comment by henryiii** [comment]
I'd be okay to add pyhf, but I think most users of pyhf already know they are going to use pyhf, and are just using that - I could be wrong, but I don't think you are likely to just happen to mix in a bit of pyhf to an analysis in progress, while that is true for awkward, vector, hist, etc. They are probably selecting a backend, and possibly adding whatever they need for that backend, etc. It's not something someone doing random HEP stuff would just happen to need - it's more of a framework than a library, and I don't think we need to put frameworks inside scikit-hep's metapackage. You can sort of think of scikit-hep's metapackage as a framework itself, IMO.

**Comment by eduardo-rodrigues** [comment]
I agree with that, Henry, and that's basically why pyhf isn't there at the moment.

**Comment by matthewfeickert** [comment]
> I'd be okay to add pyhf, but I think most users of pyhf already know they are going to use pyhf, and are just using that - I could be wrong, but I don't think you are likely to just happen to mix in a bit of pyhf to an analysis in progress, while that is true for awkward, vector, hist, etc. 

RE: `pyhf` being in I don't really have strong feelings either way. I think this (Henry's statement) is mostly true, but I think it depends on who you are (experiment wise, as statistical analysis approaches are still pretty siloed even at the LHC). Given that cavet though I can see the argument for saying leave it out if we pose the `scikit-hep` metapackge in the context of "what are tools that anyone in particle physics (LHC experiments, heavy ion community, flavour physics, neutrinos, ...) would reach for to start doing some work?".

> it's more of a framework than a library, and I don't think we need to put frameworks inside scikit-hep's metapackage. You can sort of think of scikit-hep's metapackage as a framework itself, IMO.

I wouldn't describe `pyhf` as a "framework", but I think I also have a reflexive reaction to that word given how hard we've worked to try to get people in ATLAS to mentally contrast the historical "fitting frameworks" to the approach of "libraries for statistical analysis" that `pyhf` and `cabinetry` offer.

> `pylhe` is very lightweight but also really scoped. I do not see a strong case to add it.

I think `pylhe`'s scope is sufficiently useful given how broadly used LHE files are. Though I might actually make the argument that until we either find another maintainer to work on it or we have time to clean it up it might be better to keep it out (for the time being, not forever).

> `fastjet` is scoped but many people do jets.

In my mind `fastjet` is very much in scope. I think the broader issue with including it would be that it still needs to get out of RC status and have a new release, but I'll defer to Jim here.

**Comment by eduardo-rodrigues** [comment]
Balancing the pros and cons I think we can at the very least "give it a try" and add `fastjet` and `pylhe` to the metapackage. That may actually result in more usage and feedback? Dunno. But both packages are useful and lightweight, so not a "technical" issue.
I will add them both for a future release.

**Comment by HDembinski** [comment]
> resample: seems also very scoped. No strong feelings. Do you feel we should add it to the metapackage, @HDembinski ?

It is not scoped at all, it is a very widely useful library. Bootstrapping is a standard tool to estimate statistical uncertainties. Basically everyone who does data analysis has a need for this. Whether they actually use bootstrapping is a matter of knowing about the benefits of bootstrapping and about having an easy-to-use library at hand. So, I think it should be included.

**Comment by eduardo-rodrigues** [comment]
Thank you for your comments @HDembinski. I see we are using "scoped" with different meanings. No worries. I certainly agree that bootstrapping is a powerful and common tool in analysis. I'm very happy to to the inclusion for a new release. I see that you actually have a Conda feedstock already - https://github.com/conda-forge/resample-feedstock - but no release so far because of some failures. The builds are too old to be available. Can you refresh that? Some files may require an update now that the package moved to Scikit-HEP (Also you could update the numpy dependency in meta.yaml.) Let me know when Conda is up and running, as that's necessary. Advance thanks.

**Comment by HDembinski** [comment]
Ok, I will look into conda. 

+1 on removing hepstats. I wanted to take over as maintainer, but now that we have a separate sweights library, the motivation is not there anymore.

**Comment by eduardo-rodrigues** [comment]
Little update - I released `scikit-hep 4.0.0` today, which has uproot-methods, uproot3, and awkward0 removed as agreed above.

**Comment by matthewfeickert** [comment]
Along these lines, while I always suggest that people try to avoid using LCG view environments if they can (given the massive environment bloat) and find ways to build their own bespoke environments for analysis, I've had the LCG team update `awkward`, `uproot`, `boost-histogram` in [LCG view `dev4`](https://lcginfo.cern.ch/release/dev4/) (the nightly) and had them remove `awkward0`, `uproot3`, `uproot3-methods` from `dev4` as well: https://sft.its.cern.ch/jira/browse/SPI-2229

**Comment by eduardo-rodrigues** [comment]
Good move, @matthewfeickert. We had forgotten about that ...

What do people in general think of us actually requesting the `scikit-hep` metapackage to be included in the LCG stacks? In the end most of the packages already are there, and one of the main goals of the metapackage is to make it easy to get a consistent set of org packages (that makes sense, see threads above) in one go. A large fraction of the packages in `scikit-hep` are already part of LCG anyway, hence this is a bit of branding and packaging more than providing extra functionality in LCG (and we can always request specific packages to go in independently of `scikit-hep`, if relevant, such as `uproot_browser`).

[As suggested above, we might want to remove `hepstats` from `scikit-hep`, thereby avoiding extra and tricky dependencies, but that is a detail on the proposal.]

**Comment by matthewfeickert** [comment]
I'm not necessarily against this idea, but

> In the end most of the packages already are there, and one of the main goals of the metapackage is to make it easy to get a consistent set of org packages (that makes sense, see threads above) in one go.

won't actually save that much time for us as the LCG team won't update dependencies (here all the packages in `scikit-hep`) for us and so we would still have to define each package update we want every time we requested a `scikit-hep` update. c.f. https://sft.its.cern.ch/jira/browse/SPI-2221 for an example of this.

Another potential problem is that as we use the compatible release syntax to limit packages to float at patch versions

https://github.com/scikit-hep/scikit-hep/blob/28bbc522f4633310d02ff8ce779bb10053b8b438/requirements.txt#L1-L16

this would mean that the (minor/major version) LCG release cadence for anything on this list is now relegated to the release frequency of `scikit-hep`. This would also affect the dev LCG views, meaning that to get new minor/major releases of Scikit-HEP packages staged for the next LCG release by submitting them to `dev4` would require a new release of `scikit-hep` as well.

I'm not fundamentally against putting `scikit-hep` on LCG views, but it might create more work for us rather than less. LCG views are tricky business in general, and the main reason I'm maintaining the `pyhf` release on there is because the `pyhf` team found out that someone (not us) had added it to the LCG views and it wasn't being updated yet people were still using it. So supporting `pyhf` on the LCG views is more angst-driven than out of interest. :grimacing:

**Comment by eduardo-rodrigues** [comment]
> I'm not necessarily against this idea, but

Thanks a lot @matthewfeickert for your thoughts.

> > In the end most of the packages already are there, and one of the main goals of the metapackage is to make it easy to get a consistent set of org packages (that makes sense, see threads above) in one go.
> 
> won't actually save that much time for us as the LCG team won't update dependencies (here all the packages in `scikit-hep`) for us and so we would still have to define each package update we want every time we requested a `scikit-hep` update. c.f. https://sft.its.cern.ch/jira/browse/SPI-2221 for an example of this.

I see that you are indeed requesting updates of the dependencies explicitly. I had assumed that would be done kind of automatically.

> Another potential problem is that as we use the compatible release syntax to limit packages to float at patch versions
> 
> https://github.com/scikit-hep/scikit-hep/blob/28bbc522f4633310d02ff8ce779bb10053b8b438/requirements.txt#L1-L16
> 
> this would mean that the (minor/major version) LCG release cadence for anything on this list is now relegated to the release frequency of `scikit-hep`. This would also affect the dev LCG views, meaning that to get new minor/major releases of Scikit-HEP packages staged for the next LCG release by submitting them to `dev4` would require a new release of `scikit-hep` as well.

New releases of scikit-hep is a least concern as LCG moves *far* slower. For example I have been waiting for several months for a non-dev LCG 102 for the offline LHCb stack ... In practice LCG releases would jump a bunch of scikit-hep releases, I'm sure.

I had assumed, as mentioned above, that the minor/patch versions of the org packages in scikit-hep would be frozen at the time they pip install or pick a scikit-hep tag. You seem to say it is more evolved, and what you hint at is indeed worrying since potentially requiring a lot of extra work for us. That's no good.

> I'm not fundamentally against putting `scikit-hep` on LCG views, but it might create more work for us rather than less. LCG views are tricky business in general, and the main reason I'm maintaining the `pyhf` release on there is because the `pyhf` team found out that someone (not us) had added it to the LCG views and it wasn't being updated yet people were still using it. So supporting `pyhf` on the LCG views is more angst-driven than out of interest. 😬

I see! I got pinged at some point when someone was keen on getting Particle and DecayLanguage in. Happy me. I can understand the frustration, though in general having our software in LCG is a great thing, clearly.

> I do like the point about branding though! I think that's something we could improve on in general (not in talks — there that's great and clear — but in install and use).

Let's think more on this one :).

OK, then I take the point that there are pros and cons and it may not be worth the effort at least as long as users seem happy. Fair enough. Thanks again.

**Comment by eduardo-rodrigues** [comment]
All discussions here are now resolved modulo the fact that people in general like the idea of adding fastjet to the metapackage. That is dependent on https://github.com/scikit-hep/fastjet/issues/133.

Closing at this point.
