### ISSUE TITLE
Extending scope

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/scikit-hep#178]
Perhaps this would be better as a discussion, but those aren't enabled here yet.

I wonder what the thoughts of others are on extending the scope. Presumably, the goal of the package is to be a one-stop shop for the pythonic HEP ecosystem. I would suggest that should also include `coffea` with its various nominally optional dependencies that are typically needed to run anything but benchmarks anyway: `dask`, `lpc_jobqueue` and `parsl` 

@eduardo-rodrigues @matthewfeickert @henryiii

**Comment by henryiii** [comment]
It’s really painful to work with environments that are too large. Conflicts and increased solver difficulty will come up. I’m currently fighting with the fact that Jax and TensorFlow can’t be installed in the same environment. A user just starting might want a ROOT or Anaconda like experience, though, which is why we have this package. It doesn’t have “framework” packages, those should have their own minimum dependencies anyway. A “full” install for coffea could be `install scikit-hep coffea`. A “full” install for pyhf would be `install scikit-hep pyhf`. This is meant to be a limited set of core packages that have to be able to work together. We don’t require Coffea and other frameworks be co-installable. We do require our core packages to be co installable. Remember people can always add, but they can’t take away.

**Comment by henryiii** [comment]
I’d recommend providing an example `environment.yml` as a starting point for tutorials and such, and I’d list the specific packages over this one usually. It will promote good practice and also be easy.

**Comment by andrzejnovak** [comment]
That's a fair point and I am happy to defer to your expertise here. OTOH I don't really see much use in having a meta-package if it only aggregates a handful of packages. If one were to build something finicky pulling a meta-package is probably a bad practice anyway. 

I already do provide `env.yml` in most situations, but again if that is the recommended use, aggregating 6 packages into one is even less relevant.

**Comment by henryiii** [comment]
There is some value in having all our basic packages together, like hist + uproot + awkward + mplhep + vector + etc. It gives users who are _not_ trying to use a framework like PyHF, Coffee, etc. a starting point if they don't know what they want. If they are using a framework, then they can just use that. Here I'm defining framework as something that drives the main part of what they are doing, and something that is unlikely to be mixed (normally) with other frameworks. I don't think PyHF + Cabinetry would be likely in a single environment, so why add the pain of making sure they work together? The larger this becomes, the harder it is to maintain, and the more wasted space, etc. for each install.

If we had made a "SciPy" style repo (SciHEP?) instead of smaller focused packages, what libraries would have gone it it? This is basically a list of those libraries. PyHF wouldn't fit into a SciHEP. Cabinetry wouldn't fit into SciHEP. Etc.

Also, this aggregates 14 packages, not "a handful". Without this, users would have to list up to 14 packages, which is a lot to ask for a new user who doesn't know what they are yet. I also want to work on "shared" documentation for all these packages in scikit-hep-tutorials. If you need to learn about PyHF, you'd read the PyHF docs.

**Comment by eduardo-rodrigues** [comment]
I think we effectively converged here given our strong opinions on the scope of this metapackage. Again, for anything fancier that goes beyond the dozen packages provided, one should really have an env file for something that is like `install scikit-hep coffea`, etc. This is much better than having to list 15 packages or so.

Am closing at this point.

**Comment by alexander-held** [comment]
I think the idea of what is a "core package" is going to change a lot depending on the user. I would personally call perhaps half of the packages included here truly "core". I do understand not wanting to make the environment too complex though by including lots of packages that have a potentially large amount of additional dependencies. The difference between what is in here and `coffea` in my opinion is that `coffea` is one level higher than these more fundamental components. 

> I don't think PyHF + Cabinetry would be likely in a single environment, so why add the pain of making sure they work together?

That part is easy actually — `pyhf` is a core dependency of `cabinetry`, so the compatibility comes "for free" to a user.
