### ISSUE TITLE
Use CI to create the homepage of the project

### ISSUE THREAD

**Issue by nils-braun** [scikit-hep/scikit-hep#22]
In the moment, this is a manual task. This may be automatized with every commit using e.g. travis.ci.

**Comment by eduardo-rodrigues** [comment]
That would be great, as I mentioned to you in person. For the moment I run a little script and copy things across repositories since one needs in particular to rename some of the _XXX directories created by Sphinx to XXX; and the links inside all files need to be updated accordingly, of course.
I can easily share my few commands for the job.

BTW, there is one think to keep in mind, though: at some point we will have frozen documentation for main releases, and the doc for the latest version. That's also something to keep in mind.

Maybe good to create a project idea to see if somebody has experience in these matters?

**Comment by nils-braun** [comment]
If you have a script, this is very nice. But I would actually use something like
https://github.com/Syntaf/travis-sphinx/blob/master/travis_sphinx.py
which is more or less a convenience wrapper around
https://github.com/davisp/ghp-import

Travis can also be configured to do something else on release versions etc.

I think in the end we may think about readthedocs, because there the versioning is quite easy. I have already some "experience" with this, so I may help here if you want.

**Comment by eduardo-rodrigues** [comment]
Trivial "script" that does mostly the job (then a matter of copying files across repos):
# cd to the appropriate folder
# Run the Sphinx Makefile
make -C doc html

# Fix _XXX links produced by Sphinx!
find . -type f -name "*.html" | xargs sed -i "s/_static/static/g"
fnd . -type f -name "*.html" | xargs sed -i "s/_sources/sources/g"
find . -type f -name "*.html" | xargs sed -i "s/_images/images/g"

Nothing fancy ...
I would have to see the links you give - thanks for that.

**Comment by eduardo-rodrigues** [comment]
The website now has it's own package, so this is no longer relevant.
