### ISSUE TITLE
Apply PEP8

### ISSUE THREAD

**Issue by nils-braun** [scikit-hep/scikit-hep#24]
I know, this is always the last thing people want to hear from an external contributor, but still :-)
I can take care of this, but as I would to touch multiple files, I wanted to ask first.

**Comment by eduardo-rodrigues** [comment]
I can tell you it is not the las thing I want to hear when somebody tells me "I can take care of this" ;-).
I'm in favour and simply have not complied everywhere because I do not know the full PEP8 myself.
How about we give it until the end of the week to see if somebody complains, and otherwise you can go ahead and prepare a PR with the changes to some files as a starting point? (Unless you can actually do everything in one go).
Many thanks.

**Comment by nils-braun** [comment]
Actually I think I can do this on all files at once. There are certain tools for this. I will wait until the weekend, as you have said.

**Comment by eduardo-rodrigues** [comment]
OK, will see how it looks. I'm aware of the pep8 module.
Personally I very much like the style of the doc that scikit-learn has and I'm not sure it's all PEP8-compliant.

**Comment by eduardo-rodrigues** [comment]
Sorted with pull #28.
