### ISSUE TITLE
Switch versioning to CalVer?

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/scikit-hep#264]
As the metapackage version numbers don't necessarily correspond to clear ecosystem changes but more to updates over time (or am I wrong?) should we try to signal this more clearly by changing the versioning of `scikit-hep` to CalVer instead of SemVer?

**Comment by eduardo-rodrigues** [comment]
Thank you @matthewfeickert for starting this discussion. That's a fair point that the version number does not have an exact match to SemVer since it kind of bundles a bunch of versions from its dependencies. Personally the one thing I do care about is what I wrote very explicitly in the README about the versioning, meaning:
```
Note on the versioning system:

A version scikit-hep x.y is compatible with the releases of all package dependents versions a.b.c for all c.
Major version updates are prepared every time (at least) a "package component" does the same.
Minor version updates are the typical updates, when (at least) a package goes from version a.b to a.(b+1).
Patch version updates are only done if there is some reason on the side of the metapackage itself.
```
This clearly (I hope!) explains how to understand a given version in terms of compatibilities of dependencies, which is crucial IMO. If we move to CalVer, and I understand the reason why you are making the suggestion, then we still need a way to explain compatibilities. Would it be YYYY.0M.0D? To me it does not unfortunately ticks the necessary requirements.

Comments welcome.

**Comment by alexander-held** [comment]
I personally find it unlikely that users who care about versions would be relying on the information conveyed by semver in this package. Major updates of the metapackage can quite possibly have no effect on them if they don't use a specific package included. I believe that the right way for users more sensitive to this is to control the individual components directly themselves. I would be surprised if people would be using e.g. `scikit-hep~=5.0` as a dependency (and I think this is not a good pattern).
 
To me calver makes a lot of sense here. I would realistically only ever install the latest version anyway for a quick environment setup with a stack of tools. The only compatibility point that matters in my opinion is that the packages included are compatible between each other for a given version of the metapackage.

**Comment by eduardo-rodrigues** [comment]
And why is it that you think people would not care about the versions? If they want some reproducibility they ought to care, by pinging a version of  scikit-hep. Yes if they reinstall they may get patch version differences among dependents, but that's fine and pragmatically the best one can do if not wanting to have an N-dimentional release that would make no sense.

I never said you should be using something like ` scikit-hep~=5.0`. Actually, can you tell me why you would ever do that?

If we go for CalVer then please tell me how one would go about verifying which version makes sense for their workflow? I take the point that for tutorials and others you will want the latest version 99% of the time, but again, how about for some work within the framework of an analysis where you want some preservation and reproducibility?

I can certainly move to CalVer if users prefer it, but I'm failing to see *any real benefit*. Please give me a couple. By benefit I mean something that is made easier/better with no cons.

**Comment by alexander-held** [comment]
I am not saying that people generally don't (or shouldn't) care about versions. My assumption is that for all the purposes where versions matter, people typically wouldn't use the `scikit-hep` package. At least to me it is much more natural to control the constituents I actually need myself directly in such a case, but I am perhaps also not the audience for this package.

> I never said you should be using something like  `scikit-hep~=5.0`. Actually, can you tell me why you would ever do that?

I cannot, this was sort of my point: what benefit of semver is left if you do not expect people to use this kind of pattern that relies on what semver versions convey? Maybe I am also misunderstanding something here, since in the previous paragraph you argue for pinning in a similar fashion with an extra digit ("if they reinstall they may get patch version differences").

The problem even with `~=5.0.0` is the following: imagine the one package I care about gets a crucial patch release, but in the meantime another package I do not use got a major (or even just minor) update and now the next metapackage will be `6.0.0` and my pin will not help me pick up the patch. This is why I think this cannot work for more advanced usage.

> If we go for CalVer then please tell me how one would go about verifying which version makes sense for their workflow?

I don't think that semver helps with this either. Once I go beyond the "let me just quickly test something" stage I would not recommend sticking with the metapackage. I do not think that it provides any benefits in this case and rather obfuscates which kind of version changes actually matter to me (because they're in packages I use heavily).

To me the calver benefit is that it is more suggestive of "just use the latest" than semver is, while the normal semver benefits  are diminished significantly.

**Comment by eduardo-rodrigues** [comment]
Hello folks. Apologies that this went a bit silent from my side! I have the impression that May just passed like a flash.

OK, so a hear more comments towards a change to using CalVer, and since our project is a democracy and everyone is encourage to give their opinion, the consensus is clear :-).

Just on practicalities - I should be making a release at this point. Which exact CalVer format would you suggest? Say YYYY.0M.0D?

Advance thanks.

**Comment by eduardo-rodrigues** [comment]
Hello @alexander-held, @matthewfeickert, anything special to be done for a CalVer release? I see nothing needing an update in the config/YAML files, but let me know if I overlooked anything. Otherwise I will give this a go ... Thanks.

**Comment by alexander-held** [comment]
Hi @eduardo-rodrigues. not that I am aware! @nsmith- and @lgray are switching also currently for `coffea` so they may know more.

**Comment by lgray** [comment]
Nope, you don't need to do anything special.

**Comment by eduardo-rodrigues** [comment]
Thanks for the confirmation. I was looking for places where versioning such as "v*" was put but could not find anything. Great.
