### ISSUE TITLE
Vectors not based on numpy

### ISSUE THREAD

**Issue by MarkusPrim** [scikit-hep/scikit-hep#27]
Hi,

was there a design decision that the cector class is not based on numpy arrays? One could then rely on [numpy.linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html), which provides a lot of required functionality.

Cheers,
Markus

**Comment by eduardo-rodrigues** [comment]
Hi,

Thank for getting in touch. Hope you like the project.

The short answer is no. It was important to get going with the definition of the API so a simple internal implementation was provided for the very first version of the class. But numpy arrays are indeed under the radar ... in fact some of us are about to start reviewing the vector class and a Lorentz vector class that will make it to the repository really really soon (also without an internal representation with arrays for now) and you are welcome to join the discussion/commits once that is up. Just keep an eye on things ...

I'm hence closing this issue since the redesign *is* going to happen.

Thanks,
Eduardo

**Comment by thomaskeck** [comment]
Hello,

I would also vote to design the classes so that they can benefit from SIMD (single instruction multiple data) - the strength of numpy.

**Comment by eduardo-rodrigues** [comment]
Makes sense.
BTW, how did you guys get to know about this project? I'm working hard on building a community so am very much interested ;-). Do get in touch if you want to contribute and/or have project ideas ... some are to be find already on the website and more will come.

**Comment by thomaskeck** [comment]
@eduardo-rodrigues The project was advertised by @nils-braun at KIT

**Comment by eduardo-rodrigues** [comment]
OK, so you are part of the same group. Great.
