### ISSUE TITLE
range keyword for skh_plt.hist not doing anything

### ISSUE THREAD

**Issue by frederikfaye** [scikit-hep/scikit-hep#75]
The range argument of skh_plt.hist does not seem to do anything at the moment.

```python
import numpy as np
import matplotlib.pylab as plt
from skhep.visual import MplPlotter as skh_plt
plt.rcParams['figure.figsize'] = (8,6)

np.random.seed(1001)
data = np.random.laplace(size=10000)

_ = skh_plt.hist(data, bins=1000, scale='binwidth', range=(-1,1), label='Fine Binning')
_ = skh_plt.hist(data, bins='blocks', scale='binwidth', label='Bayesian Blocks, no range', histtype='step')
_ = skh_plt.hist(data, bins='blocks', scale='binwidth', range=(-1,1), label='Bayesian Blocks, with range', histtype='step')
plt.legend(loc=2)
plt.show()
```

**Comment by eduardo-rodrigues** [comment]
Can you have a look, @pollackscience ?

**Comment by pollackscience** [comment]
Hi @frederikfaye, I confirmed that range is not working as expected with the bayesian block binning (it overrules any prior range specification).  There is a subtlety in how things are implemented: when a user calls bayesian blocks, the bins are calculated via the algorithm, and then that binning is passed to matplotlib.hist.  A user-defined set of bins overrules any call to `range`: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.hist.html
"If bins is a sequence or range is specified, autoscaling is based on the specified bin range instead of the range of x."

So now there are a few options we could go down:
    1. Do nothing, and range simply won't work with BB
    2. Range applies to the data, masking points outside of the user-defined range.
    3. Range applies to the bins after they are calculated, masking bin edges outside of range.

Option 1 seems like a cop-out.  Option 2 has the issue that it can result in a different binning, as BB is directly dependent on the input data.  Option 3 could misrepresent the final binning, since bins will probably be cut in half by the user range.  I'm inclined to go with option 3, as I see `range` as more of a zoom-in instead of a data manipulation.  I might want to throw a warning when you use range with BB, to let the user know that the bins are still being influenced by data outside of the display range.

Any suggestions or objections?

**Comment by frederikfaye** [comment]
@pollackscience Thanks for the quick answer! 

I don't know if I have much say here, but I personally would prefer the second option, for the following two reasons:

1. This is the standard in matplotlib, and is what I would expect to happen when specifying a range. 
2. I think the third option would give misleading bin heights when using `scaling=bin_width` (if you simply "zoom in" after making the bins, and the lower of upper axis limit is not perfectly aligned with a bin edge). 

The particular use case I have also needs the second option: I'm trying to make a histogram with BB in a certain range, and then make overflow bins for everything outside the specified range. In this case, I don't want the data near the range limits to potentially be represented twice (in both the BB histogram and in the overflow bins).

Finally, I don't see the problem with the range resulting in a different binning, but that may just be because I'd except the range to work by masking-out data points in the first place.

**Comment by chrisburr** [comment]
I agree that the most intuitive behaviour is

> 2. Range applies to the data, masking points outside of the user-defined range.

I think this matches with how matplotlib treats combinations of arguments such as `density=1, range=[0, 0.5]`. Overflowing data is removed and the distribution is normalised within the user supplied range as opposed to over the entire dataset.

**Comment by pollackscience** [comment]
Great, I'll implement Option 2 (masking the input data, restricting to specified range) and have it go through the PR.  In the mean time, I suggest applying the mask directly to the data:
`data[(data>xmin)&(data<xmax)]`

**Comment by pollackscience** [comment]
Forgot to mention this should be closed out @eduardo-rodrigues, range functionality updated via #76.
