### ISSUE TITLE
Documentation site down

### ISSUE THREAD

**Issue by frederikfaye** [scikit-hep/scikit-hep#81]
http://scikit-hep.org/scikit-hep/documentation.html gives a 404. Where can I read the documentation?

**Comment by eduardo-rodrigues** [comment]
Apologies! The site had a major revamp as the previous version was super out-of-date, and the doc for the scikit-hep package got trapped in a hole. I will try and get this fixed asap.

Thanks for reporting!

**Comment by frederikfaye** [comment]
@eduardo-rodrigues No worries, good to hear it's being worked on! :)

**Comment by eduardo-rodrigues** [comment]
BTW, did you notice the mailing lists we have under "get help"? We also have since a few days a Gitter channel, see https://gitter.im/Scikit-HEP/community (info to be added to the site too). You are very welcome to join to discuss about anything related to any of the packages in the org …

While on adverts: https://hepsoftwarefoundation.org/workinggroups/pyhep.html may also be of interest to you.

**Comment by frederikfaye** [comment]
@eduardo-rodrigues Very cool, thanks for the links!

**Comment by eduardo-rodrigues** [comment]
The revamp of the website has been done and the "documentation master page" https://scikit-hep.org/documentation no longer links to any doc pages for the `scikit-hep` package since the scope of the latter (to be a metapackage) is also WIP. It would not make sense to keep the old doc. For anyone still using bits and pieces of `scikit-hep` the best doc is given by the comprehensive info in docstrings. I'm hence closing this issue.
