### ISSUE TITLE
Package redesign - future of dataset submodule

### ISSUE THREAD

**Issue by marinang** [scikit-hep/scikit-hep#95]
What about it?
I don't know how many people are using it or find it useful?

Only the `NumpyDataset` , `Selection` and `Provenance` are developed. 

- `NumpyDataset` is a kind of dataframe

- I don't think `RootDataset` needs to be worked

- Is `provenance` still an important thing? (cannot be saved for now)

We could build from this work a dataset module, using additional goodies from `uproot`, `awkward-array`, `formulate` ...

**Comment by marinang** [comment]
Basically all the ingredients are already present in `pandas.DataFrame` (so no need to reinvent the wheel here) except for the `provenance` or history of operations on the dataframe. But as I said do people care about this feature?

**Comment by eduardo-rodrigues** [comment]
Thanks a lot @marinang for moving forward with this remaining submodule.

I tend to agree with you that the relevant of `ROOTDataset` is not really great, so would just drop it. Easy.

Provenance is for sure something really interesting, not the least for bookkeeping purposes, and analysis preservation. But, yes, it can only be useful if provenance information can be saved, which it can't with the present code. I would still move the code somewhere else during this reorganisation of `scikit-hep`. Later one can get back to developments.

You make good points and I'm not familiar with everything. Maybe we can chat in person sometime … For now, since we agree, will you start by removing `ROOTDataset`?

**Comment by marinang** [comment]
Ok we can say goodbye to `RootDataset`, I will open an PR to remove it.

**Comment by eduardo-rodrigues** [comment]
> Ok we can say goodbye to RootDataset, I will open an PR to remove it.

@marinang, let me know if you are too busy, in which case I can prepare the PR.

**Comment by marinang** [comment]
@eduardo-rodrigues I am doing it now :)

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues I am doing it now :)

Thanks very much!

**Comment by eduardo-rodrigues** [comment]
@marinang, will you be at CERN in the near future so that we can sit together and discuss, see suggestion above?

**Comment by marinang** [comment]
@eduardo-rodrigues I come rarely at CERN because all my meetings are video only, but I can come in the near future yes.

**Comment by eduardo-rodrigues** [comment]
OK, then drop a line if you happen to come at some point … Thanks.
